spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=app_telecom
spring.datasource.password=Telecom123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

server.port=8080


app.jwt.secret=${APP_JWT_SECRET:telecom-secreto-de-pruebas-cambiar-en-produccion-0123456789}
app.jwt.expiration-minutes=60

# ---- Credenciales para pedir el token (solo pruebas) ----
app.security.username=${APP_USER:admin}
app.security.password=${APP_PASSWORD:Admin123}
