-- Ejecutar como app_telecom en FREEPDB1 (si ya habias creado las 2 primeras tablas)

CREATE TABLE HISTORIAL_ORDEN (
    ID_HISTORIAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ORDEN NUMBER NOT NULL,
    ID_ESTADO_ANTERIOR NUMBER,
    ID_ESTADO_NUEVO NUMBER NOT NULL,
    FECHA_CAMBIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO VARCHAR2(50) NOT NULL,
    OBSERVACION VARCHAR2(200),
    CONSTRAINT FK_HIST_ORDEN FOREIGN KEY (ID_ORDEN) REFERENCES ORDEN_SERVICIO(ID_ORDEN),
    CONSTRAINT FK_HIST_ESTADO_ANT FOREIGN KEY (ID_ESTADO_ANTERIOR) REFERENCES ESTADO_ORDEN(ID_ESTADO),
    CONSTRAINT FK_HIST_ESTADO_NVO FOREIGN KEY (ID_ESTADO_NUEVO) REFERENCES ESTADO_ORDEN(ID_ESTADO)
);

CREATE INDEX IDX_HIST_ORDEN ON HISTORIAL_ORDEN(ID_ORDEN);

COMMIT;
