# Se crearan 2 tablas relacionadas orden , estados
#Tabla No. 1
CREATE TABLE ESTADO_ORDEN (
    ID_ESTADO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_ESTADO VARCHAR2(20) NOT NULL UNIQUE
);

INSERT INTO
    ESTADO_ORDEN (NOMBRE_ESTADO)
VALUES
    ('CREATED');

INSERT INTO
    ESTADO_ORDEN (NOMBRE_ESTADO)
VALUES
    ('VALIDATED');

INSERT INTO
    ESTADO_ORDEN (NOMBRE_ESTADO)
VALUES
    ('APPROVED');

INSERT INTO
    ESTADO_ORDEN (NOMBRE_ESTADO)
VALUES
    ('IN_PROGRESS');

INSERT INTO
    ESTADO_ORDEN (NOMBRE_ESTADO)
VALUES
    ('COMPLETED');

INSERT INTO
    ESTADO_ORDEN (NOMBRE_ESTADO)
VALUES
    ('CANCELLED');

#Tabla 2
CREATE TABLE ORDEN_SERVICIO (
    ID_ORDEN NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_ORDEN VARCHAR2(30) NOT NULL UNIQUE,
    ID_CLIENTE NUMBER NOT NULL,
    TIPO_SERVICIO VARCHAR2(50) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ORDEN_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_ORDEN(ID_ESTADO)
);

COMMIT;