
name: CI - Ordenes de Servicio

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  compilacion:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v5

      - name: Configurar Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Verificar estructura
        run: |
          pwd
          ls -la
          ls -la telecom-crud
          test -f telecom-crud/pom.xml

      - name: Compilar proyecto Maven
        working-directory: telecom-crud
        run: mvn --batch-mode clean verify
